alias zshrc="atom ~/.zshrc"
alias ohmyzsh="atom ~/.oh-my-zsh"
alias tree="tree -C"
alias curlhead="curl -IL"
alias http-server="python3 -m http.server"
alias ifactive="ifconfig | pcregrep -M -o '^[^\t:]+:([^\n]|\n\t)*status: active'"
alias rmpyc="find . -name '*.pyc' -delete"
alias loadenvs='export $(cat .env | xargs)'
alias dokku='~/.dokku/contrib/dokku_client.sh'
alias sshconfig='cat ~/.ssh/config'
alias dotfiles-env='eval "$(dotfiles-vars)"'
alias docker-default-env='eval "$(docker-machine env default)"'
alias ccat="colorize"
alias dns-restart="sudo killall -HUP mDNSResponder"
alias myip='dig +short myip.opendns.com @resolver1.opendns.com'
alias git-search-first-commit='git log --source --all -S'
